name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: '0 */3 * * *' # 每3小时执行一次
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: vastxie/99AI
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync check
        if: failure()
        run: |
          echo "Sync failed."
          exit 1

      - name: Trigger docker-image workflow
        if: steps.sync.outputs.changes_detected == 'true'
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/KenGrofork/NineAIQuickDeploy/dispatches \
          -d '{"event_type": "trigger-docker-image"}'
